version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    networks:
      - turreta_network
    volumes:
      - "./data:/var/lib/postgresql/data"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8889:80"
    networks:
      - turreta_network
networks:
  turreta_network:
    driver: bridge